# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('url', models.URLField(verbose_name='Advertised URL')),
                ('since', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('start_showing', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start showing')),
                ('stop_showing', models.DateTimeField(default=datetime.datetime(9999, 12, 29, 23, 59, 59, 999999, tzinfo=utc), verbose_name='Stop showing')),
            ],
            options={
                'verbose_name_plural': 'Ad Bases',
                'verbose_name': 'Ad Base',
            },
        ),
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateTimeField(auto_now_add=True, verbose_name='When')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Who')),
            ],
            options={
                'verbose_name_plural': 'Ad Clicks',
                'verbose_name': 'Ad Click',
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impression_date', models.DateTimeField(auto_now_add=True, verbose_name='When')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Who')),
            ],
            options={
                'verbose_name_plural': 'Ad Impressions',
                'verbose_name': 'Ad Impression',
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('website', models.URLField(verbose_name='Company Site')),
            ],
            options={
                'verbose_name_plural': 'Advertisers',
                'verbose_name': 'Ad Provider',
                'ordering': ('company_name',),
            },
        ),
        migrations.CreateModel(
            name='AdZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Zones',
                'verbose_name': 'Zone',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='BannerAd',
            fields=[
                ('adbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adzone.AdBase')),
                ('content', models.ImageField(upload_to='adzone/bannerads/', verbose_name='Content')),
            ],
            bases=('adzone.adbase',),
        ),
        migrations.CreateModel(
            name='TextAd',
            fields=[
                ('adbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adzone.AdBase')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            bases=('adzone.adbase',),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adzone.AdBase'),
        ),
        migrations.AddField(
            model_name='adclick',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adzone.AdBase'),
        ),
        migrations.AddField(
            model_name='adbase',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adzone.Advertiser', verbose_name='Ad Provider'),
        ),
        migrations.AddField(
            model_name='adbase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adzone.AdCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='adbase',
            name='sites',
            field=models.ManyToManyField(to='sites.Site', verbose_name='Sites'),
        ),
        migrations.AddField(
            model_name='adbase',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adzone.AdZone', verbose_name='Zone'),
        ),
    ]
